# Site settings
title: Dan Bovey
email: dan@danbovey.uk
description: Web Developer / Designer / Geek
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter: danielbovey
github:  danbovey

# Outputting
permalink: /:categories/:slug
highlighter: rouge
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from