# Site settings
title: Dan Bovey
email: dan@danbovey.uk
description: Web Developer / Designer / Geek
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danbovey.uk" # the base hostname & protocol for your site
twitter: danielbovey
github:  danbovey
youtube: danbovey
soundcloud: danbovey

# Outputting
permalink: /:categories/:title
highlighter: pygments
excerpt_separator: <!--more-->
timezone: "Europe/London"

# Build settings
markdown: kramdown